name: Publish to JSR
on:
  push:
    branches:
      - main
    paths:
      - deno.json*

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Publish package
        run: npx jsr publish
